### ISSUE TITLE
testopa-java-driver does not work with latest versions of bugzilla and testopia

### ISSUE THREAD

**Issue by Mike-M2** [kinow/testopia-java-driver#3]
Hi,
I've downloaded and installed the latest version of Bugzilla (4.4.8) and Testopia (2.5) on my Ubuntu. Later I've been trying to integrate Jenkins with Testopia with the aid of Jenkins Testopia Plugin. Though connection could be established, no information from Testopia could be successfully fetched. As the logs didn't provide any useful information I've cloned the testopia-java-driver project and started to debug it.

This is what I've found. After calling:

TestopiaAPI api = new TestopiaAPI(new URL("<ip_address>/bugzilla/xmlrpc.cgi"));
api.login("<login>","<pass>");
TestRun testRun = api.getTestRun(1);

I got the following exception:

org.apache.xmlrpc.XmlRpcException: The requested method 'TestRun.get' was not found.
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at org.mozilla.testopia.service.xmlrpc.XmlRpcTestRunService.getTestRun(XmlRpcTestRunService.java:60)
	at org.mozilla.testopia.TestopiaAPI.getTestRun(TestopiaAPI.java:191)

Later I've found the following note on Testopia's site:
https://developer.mozilla.org/en-US/docs/Mozilla/Bugzilla/Testopia
'API USERS TAKE NOTE: Positional parameters are now deprecated. All params should now be sent in a hash (struct, dict, hashmap or whatever your language of choice calls key, value pairs). Though all attempts have been made to provide continuing support for positional parameters, please be aware that some API calls may fail until you make this change. Also, future versions may remove this support completely.'

Does this mean that API call TestRun.get does not work anymore? If so, then testopia-java-driver is not working with Testopia version 2.4 and higher.

Regards,
Mike-M2.

**Comment by luisadrian17** [comment]
Yeah I have the same issue for any method that involves ".get..."

**Comment by kinow** [comment]
Hi all, 

I have long postponed working on testopia. Last time I tried, the web services for the newer versions weren't working well. I'm planning to start working on the testopia-java-driver, and the Jenkins testopia-plugin this weekend, and during the next week.

Feel free to report further issues or ask for methods that you'd need to use.

Will try my best to fix whatever is broken now, and maybe add some more flavour to this whole integration.

Cheers

**Comment by kinow** [comment]
BTW, pull requests welcome :o) in case anyone feel like writing some Java code. Most of the time that I will use for fixing issues, will be for setting up my local environment again with Perl, bugzilla, testopia and Jenkins :-/
