### ISSUE TITLE
I am not able call method like 'TestPlan.get' using xmlrpc api call .Get an error 'Method not found'.

### ISSUE THREAD

**Issue by Shubh999** [kinow/testopia-java-driver#5]
Using Bugzilla 4.2 and Testopia 2.5 . Testopia-2.5 not contain tr_xmlrpc.cgi ..

Use CookComputing.xmlrpcv2.dll for integrate Bugzilla in C#

when I login using method "User.login" and then try to get Test Plan using method "TestPlan.get" get an error 'method not found' .

Please give me any idea how to get Testopia Component like "TestPlan , TestCase , TestRun " and modify.

**Comment by lilinyueyue** [comment]
I met the similar issue.
Using Bugzilla 4.4.12 and Testopia 2.5 . I can log in with xmlrpc.cgi (or cmlrpc.cgi) with direct calling server name.dns/xmlrpc(or tr_xmlrpc), but failed to call the method TestPlan.get with error the TestPlan.get method was not found.

I did some debugging that the package and TestPlan.pm is okay to be found. the get method is in the TestPlan.pm. but I do not understand why the TestPlan.get method is not found... please help

**Comment by lilinyueyue** [comment]
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 23 Feb 2018 22:51:40 GMT
header: Server: Apache/2.4.27 (FreeBSD) OpenSSL/1.0.2l mpm-itk/2.4.7-04 mod_perl/2.0.10 Perl/v5.24.3
header: SOAPServer: SOAP::Lite/Perl/1.26
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-Xss-Protection: 1; mode=block
header: Set-Cookie: Bugzilla_login_request_cookie=noXWz5XYby; path=/; HttpOnly
header: Content-Length: 289
header: Content-Type: text/xml
================
h=<httplib.HTTPSConnection instance at 0x1040a8c68>
================
body: '<?xml version="1.0" encoding="UTF-8"?><methodResponse><fault><value><struct><member><name>faultCode</name><value><int>32000</int></value></member><member><name>faultString</name><value><string>Test Plan 10 does not exist.</string></value></member></struct></value></fault></methodResponse>'
Traceback (most recent call last):
  File "mytest.py", line 26, in <module>
    t.testplan_get(10)
  File "/Users/Admin/testopia14/testopia.py", line 777, in testplan_get
    return self.do_command("TestPlan.get", [self._number_noop(plan_id)])
  File "/Users/Admin/testopia14/testopia.py", line 503, in do_command
    raise TestopiaXmlrpcError(verb, params, e)
testopia.TestopiaXmlrpcError: Error while executing cmd 'TestPlan.get(10)' --> <Fault 32000: 'Test Plan 10 does not exist.'>

**Comment by lilinyueyue** [comment]
raise TestopiaXmlrpcError(verb, params, e)
testopia.TestopiaXmlrpcError: Error while executing cmd 'TestPlan.get(10)' --> <Fault 32000: 'Test Plan 10 does not exist.'>

**Comment by kinow** [comment]
@Shubh999 @lilinyueyue I'd have to check the status of the API in the recent releases.

Before, while working on the Jenkins plug-in and on this API, we found that there was some refactoring going on, which affected things like response type, cookies per session, etc. The last version which I tried had the API broken. Not sure if a new version has been released, so will need to find some spare time to confirm, or someone else to jump in and debug the code + Testopia code.
